### ISSUE TITLE
Keras dependency

### ISSUE THREAD

**Issue by JulietteBurtin** [xypan1232/IPMiner#2]
Hello,

I have some problem regarding the Keras dependency of IPMiner. If I use the version you recommend, Keras 0.1.2, I get the following error when running IPMiner :
Traceback (most recent call last):
  File "IPMiner.py", line 42, in <module>
    from keras.models import Sequential, model_from_config
ImportError: cannot import name 'model_from_config'

Indeed, when I look for the function 'model_from_config' in keras/models.py file, it is absent while IPMiner needs it.
I then tried to use the most recent version of Keras, 2.0.4, but I get another error :
Traceback (most recent call last):
  File "IPMiner.py", line 43, in <module>
    from keras.layers.core import Dense, Dropout, Activation, AutoEncoder, Flatten, Merge
ImportError: cannot import name 'AutoEncoder'

Indeed in keras/layers/core.py file, some classes needed by IPMiner are lacking.
How should I solve this problem ?

Thank you in advance,
Juliette

**Comment by xypan1232** [comment]
Hi,

Can you just remove model_from_config in the import, which is not used in our final code.

**Comment by JulietteBurtin** [comment]
Thanks for your quick reply.
I have removed it, but I am getting another error :
Traceback (most recent call last):
  File "IPMiner.py", line 50, in <module>
    from keras.layers.convolutional import Convolution2D, MaxPooling2D
  File "/home/chichi/Juliette/Python_3.5.2/lib/python3.5/site-packages/Keras-0.1.2-py3.5.egg/keras/layers/convolutional.py", line 6, in <module>
ImportError: cannot import name 'downsample'

**Comment by xypan1232** [comment]
i think you need update your theano (i will check my theano version later)? what is your theano version. https://github.com/Theano/Theano/issues/4337

**Comment by JulietteBurtin** [comment]
My theano version is 0.9.0, the most recent. I had to modify the file /layers/convolutional.py in the keras 0.1.2 package to adapt to the upgrading of theano :
from theano.tensor.signal import pool in place of from theano.tensor.signal import downsample and the function pool.pool_2d in place of downsample.max_pool_2d.
What is the maximum of interactions ARN-protein IPMiner can test at once ? I tried with quite huge files (531 ARN, thousands of proteins) and it did not work. Moreover, is there any limit in the number of RNA or proteins in each file ?

**Comment by xypan1232** [comment]
Hi,
I did not test the limit of IPMiner, which is up to your server with how big memory.
You will get 531 X number of protein pairs, which is very big. maybe you need split them.

**Comment by yihaicheng** [comment]
thanks, the same problem confused me for days

**Comment by bfq1206** [comment]
Hello, I want to know how you solved this problem, I also encountered the same problem：
> File "IPMiner.py", line 43, in
> from keras.layers.core import Dense, Dropout, Activation, AutoEncoder, Flatten, Merge
> ImportError: cannot import name 'AutoEncoder'

Thank you in advance,

**Comment by xypan1232** [comment]
Hi, I think you need keras 0.1.2 package with theano 0.9.0 as the backend.

**Comment by bfq1206** [comment]
Thanks for your quick reply.
I successfully ran the setup.py file in https://github.com/keras-team/keras/releases/tag/0.1.2, but I still get an error when importing keras. Do you know what this is?

>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bfq2020/anaconda3/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/bfq2020/anaconda3/lib/python3.8/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/home/bfq2020/anaconda3/lib/python3.8/site-packages/keras/backend.py", line 39, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/home/bfq2020/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/context.py)

**Comment by xypan1232** [comment]
Can you use  theano 0.9.0 as the backend.?

**Comment by bfq1206** [comment]
Yes, I checked my theano version, it is 0.9.0
>>> import theano
>>> print(theano.__version__)
0.9.0

**Comment by xypan1232** [comment]
you need configure Keras use theano as the backend

**Comment by bfq1206** [comment]
I found that I seem to be using TensorFlow as the backend. How do I configure theano as the backend? I don’t know much about this.
thank you very much!

**Comment by haichengyi** [comment]
You can modify your configuration file  "./keras/keras.json" and change tensorflow to theano.

**Comment by bfq1206** [comment]
So helpful, thank you very much

**Comment by xypan1232** [comment]
@bfq1206 great, you fixed it.
@haichengyi thanks for your answer:-)

**Comment by bfq1206** [comment]
But even though I changed my keras version and theano version, it still did not solve the problem at the beginning, and still got the following error:

ImportError: cannot import name 'AutoEncoder' from 'keras.layers' (/home/bfq2020/anaconda3/lib/python3.8/site-packages/keras/layers/__init__.py)

so sad

**Comment by xypan1232** [comment]
please use Python 2.7, not python 3.8
