### ISSUE TITLE
Exception: Layer is not connected and is not an input layer.

### ISSUE THREAD

**Issue by rominaappierdo** [xypan1232/IPMiner#7]
Hello and thank you for sharing your work.

I am trying to use IPMiner and after I ran this command

python2.7 IPMiner.py -dataset=RPI488

I am getting the following error

```
RPI488 dataset
(486, 343) (486, 256)
autoencode learning
Training the layer 1: Input 343 -> Output 256
Traceback (most recent call last):
  File "IPMiner.py", line 2248, in <module>
    IPMiner(dataset)
  File "IPMiner.py", line 2054, in IPMiner
    prefilter_train, prefilter_test, prefilter_train_bef, prefilter_test_bef = autoencoder_two_subnetwork_fine_tuning(train1, train2, train_label, test1, test2, test_label)
  File "IPMiner.py", line 1848, in autoencoder_two_subnetwork_fine_tuning
    encoders1 = multiple_layer_autoencoder(X_train1, X_test1, activation = 'sigmoid', batch_size = batch_size, nb_epoch = nb_epoch, last_dim = last_dim)
  File "IPMiner.py", line 1833, in multiple_layer_autoencoder
    ae.compile(loss='mean_squared_error', optimizer='adam')#'rmsprop')
  File "/home/appierdo/.conda/envs/ipminer/lib/python2.7/site-packages/keras/models.py", line 350, in compile
    self.X_train = self.get_input(train=True)
  File "/home/appierdo/.conda/envs/ipminer/lib/python2.7/site-packages/keras/layers/containers.py", line 64, in get_input
    return self.layers[0].get_input(train)
  File "/home/appierdo/.conda/envs/ipminer/lib/python2.7/site-packages/keras/layers/core.py", line 763, in get_input
    return self.encoder.get_input(train)
  File "/home/appierdo/.conda/envs/ipminer/lib/python2.7/site-packages/keras/layers/containers.py", line 64, in get_input
    return self.layers[0].get_input(train)
  File "/home/appierdo/.conda/envs/ipminer/lib/python2.7/site-packages/keras/layers/core.py", line 94, in get_input
    and is not an input layer.')
Exception: Layer is not connected                and is not an input layer.

```

Could you help me?

**Comment by xypan1232** [comment]
you need the version Keras-0.1.2 and the backend theano v0.9

**Comment by rominaappierdo** [comment]
Thank you very much for the prompt reply
